version: '2.4'
services:
  redis-cache:
    cpus: 1
    mem_limit: '2g'
  redis-store:
    cpus: 1
    mem_limit: '1g'
  zoekt-indexserver-0:
    cpus: 4
    mem_limit: '16g'
  zoekt-webserver-0:
    cpus: 8
    mem_limit: '16g'
  zoekt-indexserver-1:
    extends:
      file: docker-compose.yaml
      service: zoekt-indexserver-0
    cpus: 4
    mem_limit: '16g'
    environment:
      - 'HOSTNAME=zoekt-webserver-1:6070'
    volumes:
      - 'zoekt-1-shared:/data/index'
    hostname: zoekt-indexserver-1
  zoekt-webserver-1:
    extends:
      file: docker-compose.yaml
      service: zoekt-webserver-0
    cpus: 8
    mem_limit: '16g'
    environment:
      - 'HOSTNAME=zoekt-webserver-1:6070'
    volumes:
      - 'zoekt-1-shared:/data/index'
    networks:
      - sourcegraph
    hostname: zoekt-webserver-1

  gitserver-0:
    cpus: 8
    mem_limit: '25g'

  gitserver-1:
    extends:
      file: docker-compose.yaml
      service: gitserver-0
    cpus: 8
    mem_limit: '25g'

  searcher-0:
    cpus: 4
    mem_limit: '6g'
  searcher-1:
    extends:
      file: docker-compose.yaml
      service: searcher-0
    cpus: 4
    mem_limit: '6g'
    volumes:
      - 'searcher-1:/mnt/cache'

  symbols-0:
    cpus: 4
    mem_limit: '4g'
    environment:
      - USE_ROCKSKIP=true
      - ROCKSKIP_MIN_REPO_SIZE_MB=1000
  pgsql:
    cpus: 4
    mem_limit: '6g'
  sourcegraph-frontend-0:
    cpus: 6
    mem_limit: '6g'
    environment: &env_frontend
      - &env_gitserver 'SRC_GIT_SERVERS=gitserver-0:3178 gitserver-1:3178'
      - &env_searcher 'SEARCHER_URL=http://searcher-0:3181 http://searcher-1:3181'
      - &env_zoekt 'INDEXED_SEARCH_SERVERS=zoekt-webserver-0:6070 zoekt-webserver-1:6070'
  sourcegraph-frontend-1:
    extends:
      file: docker-compose.yaml
      service: sourcegraph-frontend-0
    cpus: 6
    mem_limit: '6g'
    environment: *env_frontend

  sourcegraph-frontend-internal:
    cpus: 6
    mem_limit: '6g'
    environment: *env_frontend

  worker:
    environment:
      - *env_gitserver
      - *env_searcher
      - *env_zoekt

volumes:
  gitserver-1:
  searcher-1:
  sourcegraph-frontend-1:
  zoekt-1-shared: