version: '2.4'
services:
  redis-cache:
    cpus: 1
    mem_limit: '2g'

  redis-store:
    cpus: 1
    mem_limit: '1g'

  zoekt-indexserver-0: &indexserver
    cpus: 4
    mem_limit: '24g'
  zoekt-indexserver-1: *indexserver

  zoekt-webserver-0: &webserver
    cpus: 4
    mem_limit: '24g'
  zoekt-webserver-1: *webserver

  gitserver-0:
    cpus: 8
    mem_limit: '32g'

  sourcegraph-frontend-0: &frontend
    cpus: 4
    mem_limit: '8g'
  sourcegraph-frontend-1: *frontend

  searcher-0:
    cpus: 6
    mem_limit: '12g'
    
  symbols-0:
    cpus: 4
    mem_limit: '4g'
    environment:
      - USE_ROCKSKIP=true
      - ROCKSKIP_MIN_REPO_SIZE_MB=1000