version: '2.4'
services:
  redis-cache:
    cpus: 1
    mem_limit: '1g'
  redis-store:
    cpus: 1
    mem_limit: '1g'
  zoekt-indexserver-0:
    cpus: 64
    mem_limit: '40g'
  zoekt-webserver-0:
    cpus: 8
    mem_limit: '60g'
  gitserver-0:
    cpus: 56
    mem_limit: '120g'
  searcher-0:
    cpus: 8
    mem_limit: '8g'
  symbols-0:
    cpus: 12
    mem_limit: '8g'
    environment:
      - USE_ROCKSKIP=true
      - ROCKSKIP_MIN_REPO_SIZE_MB=1000
