version: '2.4'
services:
  redis-cache:
    cpus: 1
    mem_limit: '2g'
  redis-store:
    cpus: 1
    mem_limit: '1g'
  zoekt-indexserver-0:
    cpus: 4
    mem_limit: '16g'
  zoekt-webserver-0:
    cpus: 8
    mem_limit: '16g'
  zoekt-indexserver-1:
    cpus: 4
    mem_limit: '16g'
  zoekt-webserver-1:
    cpus: 8
    mem_limit: '16g'
  gitserver-0:
    cpus: 8
    mem_limit: '25g'
  gitserver-1:
    cpus: 8
    mem_limit: '25g'
  searcher-0:
    cpus: 4
    mem_limit: '6g'
  searcher-1:
    cpus: 4
    mem_limit: '6g'
  symbols-0:
    cpus: 4
    mem_limit: '4g'
    environment:
      - USE_ROCKSKIP=true
      - ROCKSKIP_MIN_REPO_SIZE_MB=1000
  pgsql:
    cpus: 4
    mem_limit: '6g'
  sourcegraph-frontend-0:
    cpus: 6
    mem_limit: '6g'
  sourcegraph-frontend-1:
    cpus: 6
    mem_limit: '6g'
  sourcegraph-frontend-internal:
    cpus: 6
    mem_limit: '6g'
