version: '2.4'
services:
  redis-cache:
    cpus: 1
    mem_limit: '1g'
  redis-store:
    cpus: 1
    mem_limit: '1g'
  zoekt-indexserver-0:
    cpus: 8
    mem_limit: '16g'
  zoekt-webserver-0:
    cpus: 8
    mem_limit: '50g'
  gitserver-0:
    cpus: 4
