version: '2.4'
services:
  redis-cache:
    cpus: 1
    mem_limit: '1g'
  redis-store:
    cpus: 1
    mem_limit: '1g'
  zoekt-indexserver-0:
    cpus: 8
    mem_limit: '10g'
  zoekt-webserver-0:
    cpus: 8
    mem_limit: '30g'