version: '2.4'
services:
  redis-cache:
    cpus: 1
    mem_limit: '1g'
  redis-store:
    cpus: 1
    mem_limit: '1g'
  zoekt-indexserver-0:
    cpus: 8
    mem_limit: '10g'
  zoekt-webserver-0:
    cpus: 8
    mem_limit: '30g'
  caddy:
    environment:
      - 'XDG_DATA_HOME=/caddy-storage/data'
      - 'XDG_CONFIG_HOME=/caddy-storage/config'
      - 'SRC_FRONTEND_ADDRESSES=sourcegraph-frontend-0:3080'
      - 'SRC_SITE_ADDRESS=ec2-54-188-111-47.us-west-2.compute.amazonaws.com'
      - 'SRC_ACME_EMAIL=beatrix@sourcegraph.com'
    volumes:
      - 'caddy:/caddy-storage'
      #
      # IMPORTANT: if a customer uses a reverse proxy in front of Caddy
      # the configuration files below must be updated to include trusted_proxies
      # 
      # Comment out the following line when using HTTPS with either Let's Encrypt or custom certificates
      # - '../caddy/builtins/http.Caddyfile:/etc/caddy/Caddyfile'
      #
      # Uncomment the following line when using HTTPS with Let's Encrypt's staging environment
      # - '../caddy/builtins/https.lets-encrypt-staging.Caddyfile:/etc/caddy/Caddyfile'
      #
      # Uncomment the following line when using HTTPS with Let's Encrypt's production environment
      # IMPORTANT: Strongly recommended to test with the staging configuration above first, see that file for details.
      - '../caddy/builtins/https.lets-encrypt-prod.Caddyfile:/etc/caddy/Caddyfile'
      #
      # Uncomment the following line when using HTTPS with custom certificates
      # - '../caddy/builtins/https.custom-cert.Caddyfile:/etc/caddy/Caddyfile'
      #
      # Uncomment / update the following line when using HTTPS with custom certificates
      # - '/LOCAL/CERT/PATH.pem:/sourcegraph.pem'
      #
      # Uncomment / update the following line when using HTTPS with custom certificates
      # - '/LOCAL/KEY/PATH.key:/sourcegraph.key'
