version: '2.4'
services:
  redis-cache:
    cpus: 1
    mem_limit: '1g'

  redis-store:
    cpus: 1
    mem_limit: '1g'
  migrator:
    cpus: 0.5
    mem_limit: '1g'
  sourcegraph-frontend-0:
    cpus: 4
    mem_limit: '32g'
  sourcegraph-frontend-internal:
    cpus: 4
    mem_limit: '32g'
  gitserver-0:
    cpus: 15
    mem_limit: '96g'
  zoekt-indexserver-0:
    cpus: 8
    mem_limit: '64g'
  zoekt-webserver-0:
    cpus: 24
    mem_limit: '64g'
  searcher-0:
    cpus: 4
    mem_limit: '24g'
  github-proxy:
    cpus: 0.5
    mem_limit: '2g'
  precise-code-intel-worker:
    cpus: 0.5
    mem_limit: '8g'
  repo-updater:
    cpus: 2
    mem_limit: '8g'
  worker:
    cpus: 1
    mem_limit: '8g'
  syntect-server:
    cpus: 4
    mem_limit: '12g'
  symbols-0:
    cpus: 4
    mem_limit: '16g'
  grafana:
    cpus: 1
    mem_limit: '2g'
  cadvisor:
    cpus: 0.5
    mem_limit: '2g'
  jaeger:
    cpus: 0.5
    mem_limit: '1g'
  pgsql:
    cpus: 8
    mem_limit: '32g'
  codeintel-db:
    cpus: 2
    mem_limit: '16g'
  codeintel-db-exporter:
    cpus: 0.1
    mem_limit: '0.1g'
  codeinsights-db:
    cpus: 0.1
    mem_limit: '2g'
  codeinsights-db-exporter:
    cpus: 0.1
    mem_limit: '0.1g'
  minio:
    cpus: 0.5
    mem_limit: '2g'
