version: '2.4'
services:
  redis-cache:
    cpus: 1
    mem_limit: '1g'
  redis-store:
    cpus: 1
    mem_limit: '1g'
  zoekt-indexserver-0:
    cpus: 6
    mem_limit: '24g'
  zoekt-webserver-0:
    cpus: 6
    mem_limit: '16g'
  gitserver-0:
    cpus: 6
    mem_limit: '20g'
  symbols-0:
    environment:
      - USE_ROCKSKIP=true
      - ROCKSKIP_MIN_REPO_SIZE_MB=1000