version: '2.4'
services:
  redis-cache:
    cpus: 1
    mem_limit: '7g'

  redis-store:
    cpus: 1
    mem_limit: '1g'

  zoekt-indexserver-0: &indexserver
    cpus: 16
    mem_limit: '16g'
  zoekt-indexserver-1: *indexserver
  zoekt-indexserver-2: *indexserver
  zoekt-indexserver-3: *indexserver
  zoekt-indexserver-4: *indexserver
  zoekt-indexserver-5: *indexserver
  zoekt-indexserver-6: *indexserver
  zoekt-indexserver-7: *indexserver
  zoekt-indexserver-8: *indexserver
  zoekt-indexserver-9: *indexserver

  zoekt-webserver-0: &webserver
    cpus: 16
    mem_limit: '26g'
  zoekt-webserver-1: *webserver
  zoekt-webserver-2: *webserver
  zoekt-webserver-3: *webserver    
  zoekt-webserver-4: *webserver  
  zoekt-webserver-5: *webserver
  zoekt-webserver-6: *webserver  
  zoekt-webserver-7: *webserver  
  zoekt-webserver-8: *webserver  
  zoekt-webserver-9: *webserver  

  gitserver-0: &gitserver
    cpus: 12
    mem_limit: '24g'
  gitserver-1: *gitserver
  gitserver-2: *gitserver
  gitserver-3: *gitserver
  gitserver-4: *gitserver

  searcher-0: &searcher
    cpus: 24
    mem_limit: '16g'
  searcher-1: *searcher
  searcher-2: *searcher

  symbols-0: &symbols
    cpus: 12
    mem_limit: '24g'
    environment:
      - USE_ROCKSKIP=true
      - ROCKSKIP_MIN_REPO_SIZE_MB=1000
  symbols-1: *symbols

  pgsql:
    cpus: 16
    mem_limit: '32g'


  sourcegraph-frontend-0: &frontend
    cpus: 8
    mem_limit: '8g'
  sourcegraph-frontend-1: *frontend
  sourcegraph-frontend-2: *frontend
  sourcegraph-frontend-3: *frontend
  sourcegraph-frontend-4: *frontend
  sourcegraph-frontend-5: *frontend
  sourcegraph-frontend-6: *frontend
  sourcegraph-frontend-7: *frontend
  sourcegraph-frontend-8: *frontend
  sourcegraph-frontend-9: *frontend
  sourcegraph-frontend-internal: *frontend

  caddy:
    environment:
      - 'XDG_DATA_HOME=/caddy-storage/data'
      - 'XDG_CONFIG_HOME=/caddy-storage/config'
      - 'SRC_FRONTEND_ADDRESSES=sourcegraph-frontend-0:3080 sourcegraph-frontend-1:3080 sourcegraph-frontend-2:3080 sourcegraph-frontend-3:3080 sourcegraph-frontend-4:3080 sourcegraph-frontend-5:3080 sourcegraph-frontend-6:3080 sourcegraph-frontend-7:3080 sourcegraph-frontend-8:3080 sourcegraph-frontend-9:3080'
      # Uncomment & update this line when using Let's Encrypt or custom HTTPS certificates:
      # - 'SRC_SITE_ADDRESS=ec2-52-35-104-18.us-west-2.compute.amazonaws.com'
      - 'SRC_SITE_ADDRESS=ec2-34-221-201-222.us-west-2.compute.amazonaws.com'
      #
      # Uncomment & update the following line when using HTTPS with Let's Encrypt
      - 'SRC_ACME_EMAIL=beatrix@sourcegraph.com'
    volumes:
      - 'caddy:/caddy-storage'
      #
      # IMPORTANT: if a customer uses a reverse proxy in front of Caddy
      # the configuration files below must be updated to include trusted_proxies
      #
      # Comment out the following line when using HTTPS with either Let's Encrypt or custom certificates
      # - '../caddy/builtins/http.Caddyfile:/etc/caddy/Caddyfile'
      #
      # Uncomment the following line when using HTTPS with Let's Encrypt's staging environment
      # - '../caddy/builtins/https.lets-encrypt-staging.Caddyfile:/etc/caddy/Caddyfile'
      #
      # Uncomment the following line when using HTTPS with Let's Encrypt's production environment
      # IMPORTANT: Strongly recommended to test with the staging configuration above first, see that file for details.
      - '../caddy/builtins/https.lets-encrypt-prod.Caddyfile:/etc/caddy/Caddyfile'
