version: '2.4'
services:
  redis-cache:
    cpus: 1
    mem_limit: '1g'
  redis-store:
    cpus: 1
    mem_limit: '1g'
  zoekt-indexserver-0:
    cpus: 24
    mem_limit: '65g'
  zoekt-webserver-0:
    cpus: 8
    mem_limit: '65g'
  gitserver-0:
    cpus: 32
    mem_limit: '124g'
  searcher-0:
    cpus: 8
    mem_limit: '8g'
  symbols-0:
    cpus: 12
    mem_limit: '6g'
    environment:
      - USE_ROCKSKIP=true
      - ROCKSKIP_MIN_REPO_SIZE_MB=1000